"""add_onboarding_progress_to_candidate

Revision ID: b78895d1fb4b
Revises: b92a4db8bc54
Create Date: 2026-04-24 17:12:36.538042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78895d1fb4b'
down_revision: Union[str, None] = 'b92a4db8bc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('candidate_profiles', sa.Column('onboarding_step', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('candidate_profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'onboarding_completed')
    op.drop_column('candidate_profiles', 'onboarding_step')
    # ### end Alembic commands ###
