"""add_cover_letter_status_and_content_json

Revision ID: be0f67fcffd6
Revises: c3a1f2e4d56b
Create Date: 2026-04-27 12:49:06.891147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be0f67fcffd6'
down_revision: Union[str, None] = 'c3a1f2e4d56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cover_letters', sa.Column('content_json', sa.JSON(), nullable=True))
    op.add_column('cover_letters', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('cover_letters', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cover_letters', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_cover_letters_user_created', 'cover_letters', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint('cover_letters_job_id_fkey', 'cover_letters', type_='foreignkey')
    op.create_foreign_key(None, 'cover_letters', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.create_foreign_key('cover_letters_job_id_fkey', 'cover_letters', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_cover_letters_user_created', table_name='cover_letters')
    op.alter_column('cover_letters', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cover_letters', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cover_letters', 'status')
    op.drop_column('cover_letters', 'content_json')
    op.drop_column('cover_letters', 'job_description')
    # ### end Alembic commands ###
